name: Azure AI Foundry Agent Evaluations

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  run-action:
    name: Run Azure AI Foundry Agent Evaluations
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Azure AI Agent Evaluation
      uses: microsoft/ai-agent-evals@v1-beta
      with:
        deployment-name: "gpt-40-mini"
        azure-aiproject-connection-string: ${{ secrets.AZURE_AI_PROJECT_CONNECTION_STRING }}
        agent-ids: ${{ secrets.AZURE_AI_AGENT_IDS }}
        # evaluation-result-view: "all-scores"
        data-path: "data/agent-evals.json"